server:
  port: 8383


turbine:
  appConfig: author,credentials,post,category
  aggregator:
    clusterConfig: AUTHOR,CREDENTIALS,POST,CATEGORY

eureka:
  client:
    region: default
    registryFetchIntervalSeconds : 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
