#Database Configuration#
server:
  port: 8282

spring:
  rabbitmq:
    port: 5672
    host: 'localhost'
    username: guest
    password: guest
  datasource:
    url: jdbc:mysql://localhost/restful_blog_author
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    show-sql : true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
eureka:
  instance:
    reaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false